# Generated by Django 4.0.4 on 2022-07-27 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_followerscount_likepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='liked_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 5, 33, 34, 867304)),
        ),
    ]
