# Generated by Django 4.0.4 on 2022-08-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_post_str_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='str_id',
        ),
    ]
