# Generated by Django 4.0.4 on 2022-08-15 11:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_remove_post_str_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_post_id',
            field=models.UUIDField(default=uuid.uuid4, verbose_name=str),
        ),
    ]
