# Generated by Django 4.0.4 on 2022-07-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_alter_likepost_liked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='owner',
            field=models.CharField(default='', max_length=100),
        ),
    ]
